### ISSUE TITLE
RuntimeError: Unknown layout

### ISSUE THREAD

**Issue by liangwenge740** [drprojects/superpoint_transformer#142]
Hello,Thank you for sharing this project,and I encounter a problem.

```
[2024-07-20 08:34:23,163][__main__][INFO] - Instantiating trainer <pytorch_lightning.Trainer>
GPU available: True (cuda), used: True
TPU available: False, using: 0 TPU cores
HPU available: False, using: 0 HPUs
[2024-07-20 08:34:23,179][__main__][INFO] - Starting testing!
Processing...
  0%|                                                   | 0/261 [00:01<?, ?it/s]
[2024-07-20 08:34:24,293][src.utils.utils][ERROR] - 
Traceback (most recent call last):
  File "/home/lwg/superpoint/src/utils/utils.py", line 45, in wrap
    metric_dict, object_dict = task_func(cfg=cfg)
  File "src/eval.py", line 106, in evaluate
    trainer.test(model=model, datamodule=datamodule, ckpt_path=cfg.ckpt_path)
  File "/home/lwg/anaconda3/envs/spt/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 753, in test
    return call._call_and_handle_interrupt(
  File "/home/lwg/anaconda3/envs/spt/lib/python3.8/site-packages/pytorch_lightning/trainer/call.py", line 44, in _call_and_handle_interrupt
    return trainer_fn(*args, **kwargs)
  File "/home/lwg/anaconda3/envs/spt/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 793, in _test_impl
    results = self._run(model, ckpt_path=ckpt_path)
  File "/home/lwg/anaconda3/envs/spt/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 946, in _run
    self._data_connector.prepare_data()
  File "/home/lwg/anaconda3/envs/spt/lib/python3.8/site-packages/pytorch_lightning/trainer/connectors/data_connector.py", line 93, in prepare_data
    call._call_lightning_datamodule_hook(trainer, "prepare_data")
  File "/home/lwg/anaconda3/envs/spt/lib/python3.8/site-packages/pytorch_lightning/trainer/call.py", line 181, in _call_lightning_datamodule_hook
    return fn(*args, **kwargs)
  File "/home/lwg/superpoint/src/datamodules/base.py", line 144, in prepare_data
    self.dataset_class(
  File "/home/lwg/superpoint/src/datasets/base.py", line 223, in __init__
    super().__init__(root, transform, pre_transform, pre_filter)
  File "/home/lwg/anaconda3/envs/spt/lib/python3.8/site-packages/torch_geometric/data/in_memory_dataset.py", line 57, in __init__
    super().__init__(root, transform, pre_transform, pre_filter, log)
  File "/home/lwg/anaconda3/envs/spt/lib/python3.8/site-packages/torch_geometric/data/dataset.py", line 97, in __init__
    self._process()
  File "/home/lwg/superpoint/src/datasets/base.py", line 647, in _process
    self.process()
  File "/home/lwg/superpoint/src/datasets/base.py", line 682, in process
    self._process_single_cloud(p)
  File "/home/lwg/superpoint/src/datasets/base.py", line 710, in _process_single_cloud
    nag = self.pre_transform(data)
  File "/home/lwg/anaconda3/envs/spt/lib/python3.8/site-packages/torch_geometric/transforms/compose.py", line 24, in __call__
    data = transform(data)
  File "/home/lwg/superpoint/src/transforms/transforms.py", line 23, in __call__
    return self._process(x)
  File "/home/lwg/superpoint/src/transforms/sampling.py", line 151, in _process
    cluster = grid_cluster(coords, torch.ones(3, device=coords.device))
  File "/home/lwg/anaconda3/envs/spt/lib/python3.8/site-packages/torch_cluster/grid.py", line 34, in grid_cluster
    return torch.ops.torch_cluster.grid(pos, size, start, end)
  File "/home/lwg/anaconda3/envs/spt/lib/python3.8/site-packages/torch/_ops.py", line 755, in __call__
    return self._op(*args, **(kwargs or {}))
RuntimeError: Unknown layout
```

Can you help me?

**Comment by drprojects** [comment]
Hi @liangwenge740, this sounds a bit like issue #99, although arising in a differernt part of the code. Can you please try adjusting your torch version as suggested there and let us know how that goes ?

**Comment by liangwenge740** [comment]
Thank you ,I install torch2.1.0 and FRNN again , and solve this problem.
