### ISSUE TITLE
single_plane_model() got an unexpected keyword argument 'threshold'

### ISSUE THREAD

**Issue by dzj727** [drprojects/superpoint_transformer#166]
hello,I have encountered a  problem.The error is:

```
Traceback (most recent call last):
  File "src/train.py", line 140, in main
    metric_dict, _ = train(cfg)
  File "/home/coral/SPG/superpoint_transformer/src/utils/utils.py", line 48, in wrap
    raise ex
  File "/home/coral/SPG/superpoint_transformer/src/utils/utils.py", line 45, in wrap
    metric_dict, object_dict = task_func(cfg=cfg)
  File "src/train.py", line 115, in train
    trainer.fit(model=model, datamodule=datamodule, ckpt_path=cfg.get("ckpt_path"))
  File "/home/coral/miniconda3/envs/spt/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 538, in fit
    call._call_and_handle_interrupt(
  File "/home/coral/miniconda3/envs/spt/lib/python3.8/site-packages/pytorch_lightning/trainer/call.py", line 47, in _call_and_handle_interrupt
    return trainer_fn(*args, **kwargs)
  File "/home/coral/miniconda3/envs/spt/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 574, in _fit_impl
    self._run(model, ckpt_path=ckpt_path)
  File "/home/coral/miniconda3/envs/spt/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 941, in _run
    self._data_connector.prepare_data()
  File "/home/coral/miniconda3/envs/spt/lib/python3.8/site-packages/pytorch_lightning/trainer/connectors/data_connector.py", line 93, in prepare_data
    call._call_lightning_datamodule_hook(trainer, "prepare_data")
  File "/home/coral/miniconda3/envs/spt/lib/python3.8/site-packages/pytorch_lightning/trainer/call.py", line 189, in _call_lightning_datamodule_hook
    return fn(*args, **kwargs)
  File "/home/coral/SPG/superpoint_transformer/src/datamodules/base.py", line 144, in prepare_data
    self.dataset_class(
  File "/home/coral/SPG/superpoint_transformer/src/datasets/base.py", line 223, in __init__
    super().__init__(root, transform, pre_transform, pre_filter)
  File "/home/coral/miniconda3/envs/spt/lib/python3.8/site-packages/torch_geometric/data/in_memory_dataset.py", line 57, in __init__
    super().__init__(root, transform, pre_transform, pre_filter, log)
  File "/home/coral/miniconda3/envs/spt/lib/python3.8/site-packages/torch_geometric/data/dataset.py", line 97, in __init__
    self._process()
  File "/home/coral/SPG/superpoint_transformer/src/datasets/base.py", line 647, in _process
    self.process()
  File "/home/coral/SPG/superpoint_transformer/src/datasets/base.py", line 682, in process
    self._process_single_cloud(p)
  File "/home/coral/SPG/superpoint_transformer/src/datasets/base.py", line 710, in _process_single_cloud
    nag = self.pre_transform(data)
  File "/home/coral/miniconda3/envs/spt/lib/python3.8/site-packages/torch_geometric/transforms/compose.py", line 24, in __call__
    data = transform(data)
  File "/home/coral/SPG/superpoint_transformer/src/transforms/transforms.py", line 23, in __call__
    return self._process(x)
  File "/home/coral/SPG/superpoint_transformer/src/transforms/point.py", line 327, in _process
    model = single_plane_model(pos_trimmed, **self.kwargs)
TypeError: single_plane_model() got an unexpected keyword argument 'threshold'
```

Here's the code

![15A](https://github.com/user-attachments/assets/a2836d28-2f7c-4e59-a8f4-1cc9fe17dfec)

Can you help me？Please! 
Thank you!

**Comment by drprojects** [comment]
Hi @dzj727, good catch ! This was indeed an error on my part after a recent modification I made. I just pushed a new commit that should tackle this issue. Can you please update to the latest version, try again, and let me know if it did ?

### PS: If you ❤️ or simply use this project, don't forget to give the repository a ⭐, it means a lot to us !

**Comment by dzj727** [comment]
Thank you very much for your prompt response and hard work! I have tried the latest version and it's working properly now. Your solution and fix were extremely helpful to me. Thanks again! If I encounter any further issues, I will definitely reach out to you for advice.
