### ISSUE TITLE
TypeError: metaclass conflict: the metaclass of a derived class must be a (non-strict) subclass of the metaclasses of all its bases

### ISSUE THREAD

**Issue by yfq512** [drprojects/superpoint_transformer#172]
### ✅ Code of conduct checklist

- [X] 🌱 I am using the **_latest version_** of the [code](https://github.com/drprojects/superpoint_transformer/tree/master).
- [X] 👩‍💻 I made sure the bug concerns the official [project's codebase](https://github.com/drprojects/superpoint_transformer/tree/master) and not something I coded myself on top of it. (We only provide support for code we wrote and released ourselves).
- [X] 🔎 I took appropriate **_time_** to investigate the problem before filing an issue, but am unable to solve it myself.
- [X] 📙 I **_thoroughly_** went through the [README](https://github.com/drprojects/superpoint_transformer/blob/master/README.md), but could not find the solution there.
- [X] 📘 I **_thoroughly_** went through the tutorial [slides](media/superpoint_transformer_tutorial.pdf), [notebook](notebooks/superpoint_transformer_tutorial.ipynb), and [video](https://www.youtube.com/watch?v=2qKhpQs9gJw), but could not find the solution there.
- [X] 📗 I **_thoroughly_** went through the [documentation](https://github.com/drprojects/superpoint_transformer/tree/master/docs), but could not find the solution there.
- [X] 📜 I went through the **_docstrings_** and **_comments_** in the [source code](https://github.com/drprojects/superpoint_transformer/tree/master) parts relevant to my problem, but could not find the solution there.
- [X] 👩‍🔧 I searched for [**_similar issues_**](https://github.com/drprojects/superpoint_transformer/issues), but could not find the solution there.
- [X] 🔎 I made sure my bug is related to the [project's codebase](https://github.com/drprojects/superpoint_transformer/tree/master) and is not in fact a sub-dependency issue (e.g.: FRNN installation issue, PyTorch installation issue, PyTorch Geometric not installed with GPU support, ...).
- [X] ⭐ Since I am showing interest in the project, I took the time to give the [repo](https://github.com/drprojects/superpoint_transformer/tree/master) a ⭐ to show support. **Please do, it means a lot to us !**

### 🐛 Describe the bug

run train code "python src/train.py experiment=semantic/s3dis_11g datamodule.fold=5" error:

### 📜 Log output

```shell
superpoint_transformer# python src/train.py experiment=semantic/s3dis_11g datamodule.fold=5
Traceback (most recent call last):
  File "src/train.py", line 49, in <module>
    from src import utils
  File "/data/docker/yfq/openmmlab/3d_det/superpoint_transformer/src/__init__.py", line 2, in <module>
    import src.data
  File "/data/docker/yfq/openmmlab/3d_det/superpoint_transformer/src/data/__init__.py", line 5, in <module>
    from .data import *
  File "/data/docker/yfq/openmmlab/3d_det/superpoint_transformer/src/data/data.py", line 972, in <module>
    class Batch(PyGBatch, Data):
TypeError: metaclass conflict: the metaclass of a derived class must be a (non-strict) subclass of the metaclasses of all its bases

```

### 🤖 Steps to reproduce the bug

```
python src/train.py experiment=semantic/s3dis_11g datamodule.fold=5
```

### 🖥️ Environment

```shell
Collecting environment information...
PyTorch version: 2.2.0
Is debug build: False
CUDA used to build PyTorch: 11.8
ROCM used to build PyTorch: N/A

OS: Ubuntu 18.04.5 LTS (x86_64)
GCC version: (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
Clang version: Could not collect
CMake version: Could not collect
Libc version: glibc-2.27

Python version: 3.8.20 (default, Oct  3 2024, 15:24:27)  [GCC 11.2.0] (64-bit runtime)
Python platform: Linux-6.5.0-27-generic-x86_64-with-glibc2.17
Is CUDA available: True
CUDA runtime version: 11.8.89
CUDA_MODULE_LOADING set to: LAZY
GPU models and configuration: GPU 0: NVIDIA GeForce RTX 4090
Nvidia driver version: 550.67
cuDNN version: Probably one of the following:
/usr/lib/x86_64-linux-gnu/libcudnn.so.8.0.5
/usr/lib/x86_64-linux-gnu/libcudnn_adv_infer.so.8.0.5
/usr/lib/x86_64-linux-gnu/libcudnn_adv_train.so.8.0.5
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_infer.so.8.0.5
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_train.so.8.0.5
/usr/lib/x86_64-linux-gnu/libcudnn_ops_infer.so.8.0.5
/usr/lib/x86_64-linux-gnu/libcudnn_ops_train.so.8.0.5
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Architecture:        x86_64
CPU op-mode(s):      32-bit, 64-bit
Byte Order:          Little Endian
CPU(s):              80
On-line CPU(s) list: 0-79
Thread(s) per core:  2
Core(s) per socket:  20
Socket(s):           2
NUMA node(s):        2
Vendor ID:           GenuineIntel
CPU family:          6
Model:               85
Model name:          Intel(R) Xeon(R) Gold 6133 CPU @ 2.50GHz
Stepping:            4
CPU MHz:             1000.000
CPU max MHz:         3000.0000
CPU min MHz:         1000.0000
BogoMIPS:            5000.00
Virtualization:      VT-x
L1d cache:           32K
L1i cache:           32K
L2 cache:            1024K
L3 cache:            28160K
NUMA node0 CPU(s):   0-19,40-59
NUMA node1 CPU(s):   20-39,60-79
Flags:               fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc art arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid dca sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch cpuid_fault epb cat_l3 cdp_l3 invpcid_single pti intel_ppin ssbd mba ibrs ibpb stibp tpr_shadow flexpriority ept vpid ept_ad fsgsbase tsc_adjust bmi1 hle avx2 smep bmi2 erms invpcid rtm cqm mpx rdt_a avx512f avx512dq rdseed adx smap clflushopt clwb intel_pt avx512cd avx512bw avx512vl xsaveopt xsavec xgetbv1 xsaves cqm_llc cqm_occup_llc cqm_mbm_total cqm_mbm_local dtherm ida arat pln pts vnmi pku ospke md_clear flush_l1d arch_capabilities

Versions of relevant libraries:
[pip3] numpy==1.24.3
[pip3] pytorch-lightning==2.4.0
[pip3] torch==2.2.0
[pip3] torch-geometric==2.6.1
[pip3] torch_scatter==2.1.2
[pip3] torchaudio==2.2.0
[pip3] torchmetrics==1.5.2
[pip3] torchvision==0.17.0
[pip3] triton==2.2.0
[conda] blas                      1.0                         mkl
[conda] cuda-cudart               11.8.89                       0    nvidia/label/cuda-11.8.0
[conda] cuda-cudart-dev           11.8.89                       0    nvidia/label/cuda-11.8.0
[conda] cuda-cupti                11.8.87                       0    nvidia/label/cuda-11.8.0
[conda] cuda-libraries            11.8.0                        0    nvidia/label/cuda-11.8.0
[conda] cuda-libraries-dev        11.8.0                        0    nvidia/label/cuda-11.8.0
[conda] cuda-nvrtc                11.8.89                       0    nvidia/label/cuda-11.8.0
[conda] cuda-nvrtc-dev            11.8.89                       0    nvidia/label/cuda-11.8.0
[conda] cuda-nvtx                 11.8.86                       0    nvidia/label/cuda-11.8.0
[conda] cuda-runtime              11.8.0                        0    nvidia/label/cuda-11.8.0
[conda] cudatoolkit               11.8.0               h6a678d5_0
[conda] ffmpeg                    4.3                  hf484d3e_0    pytorch
[conda] libcublas                 11.11.3.6                     0    nvidia/label/cuda-11.8.0
[conda] libcublas-dev             11.11.3.6                     0    nvidia/label/cuda-11.8.0
[conda] libcufft                  10.9.0.58                     0    nvidia/label/cuda-11.8.0
[conda] libcufft-dev              10.9.0.58                     0    nvidia/label/cuda-11.8.0
[conda] libcurand                 10.3.0.86                     0    nvidia/label/cuda-11.8.0
[conda] libcurand-dev             10.3.0.86                     0    nvidia/label/cuda-11.8.0
[conda] libcusolver               11.4.1.48                     0    nvidia/label/cuda-11.8.0
[conda] libcusolver-dev           11.4.1.48                     0    nvidia/label/cuda-11.8.0
[conda] libcusparse               11.7.5.86                     0    nvidia/label/cuda-11.8.0
[conda] libcusparse-dev           11.7.5.86                     0    nvidia/label/cuda-11.8.0
[conda] libjpeg-turbo             2.0.0                h9bf148f_0    pytorch
[conda] mkl                       2023.1.0         h213fc3f_46344
[conda] mkl-service               2.4.0            py38h5eee18b_1
[conda] mkl_fft                   1.3.8            py38h5eee18b_0
[conda] mkl_random                1.2.4            py38hdb19cb5_0
[conda] numpy                     1.24.3           py38hf6e8229_1
[conda] numpy-base                1.24.3           py38h060ed82_1
[conda] pytorch                   2.2.0           py3.8_cuda11.8_cudnn8.7.0_0    pytorch
[conda] pytorch-cuda              11.8                 h7e8668a_6    pytorch
[conda] pytorch-lightning         2.4.0                    pypi_0    pypi
[conda] pytorch-mutex             1.0                        cuda    pytorch
[conda] torch-geometric           2.6.1                    pypi_0    pypi
[conda] torch-scatter             2.1.2                    pypi_0    pypi
[conda] torchaudio                2.2.0                py38_cu118    pytorch
[conda] torchmetrics              1.5.2                    pypi_0    pypi
[conda] torchtriton               2.2.0                      py38    pytorch
[conda] torchvision               0.17.0               py38_cu118    pytorch

```
```

**Comment by drprojects** [comment]
I tried to reproduce this error but things work fine on my end.

My intuition is that you are using the latest version of the code but probably have not noticed that v2.1.0 introduced a breaking change in our data structures, which requires re-preprocessing your datasets. See our [CHANGELOG.md](https://github.com/drprojects/superpoint_transformer/blob/master/CHANGELOG.md).

Please re-open this this issue if the problem persists after re-running your dataset preprocessing.
