### ISSUE TITLE
mat1 and mat2 shapes cannot be multiplied (79824x4 and 10x32)

### ISSUE THREAD

**Issue by BHANUBBOY** [drprojects/superpoint_transformer#174]
hlw @drprojects  we were actuly training superpoint tranformer model on a custom dataset but we are gtetting this error after the training started : Error executing job with overrides: ['experiment=semantic/dales']
Traceback (most recent call last):
  File "src/train.py", line 140, in main
    metric_dict, _ = train(cfg)
  File "/DATA2/dse411p/Group6_superpoint/superpoint_transformer/src/utils/utils.py", line 48, in wrap
    raise ex
  File "/DATA2/dse411p/Group6_superpoint/superpoint_transformer/src/utils/utils.py", line 45, in wrap
    metric_dict, object_dict = task_func(cfg=cfg)
  File "src/train.py", line 115, in train
    trainer.fit(model=model, datamodule=datamodule, ckpt_path=cfg.get("ckpt_path"))
  File "/DATA2/dse411p/Group6_superpoint/superenv/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 538, in fit
    call._call_and_handle_interrupt(
  File "/DATA2/dse411p/Group6_superpoint/superenv/lib/python3.8/site-packages/pytorch_lightning/trainer/call.py", line 47, in _call_and_handle_interrupt
    return trainer_fn(*args, **kwargs)
  File "/DATA2/dse411p/Group6_superpoint/superenv/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 574, in _fit_impl
    self._run(model, ckpt_path=ckpt_path)
  File "/DATA2/dse411p/Group6_superpoint/superenv/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 981, in _run
    results = self._run_stage()
  File "/DATA2/dse411p/Group6_superpoint/superenv/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1023, in _run_stage
    self._run_sanity_check()
  File "/DATA2/dse411p/Group6_superpoint/superenv/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1052, in _run_sanity_check
    val_loop.run()
  File "/DATA2/dse411p/Group6_superpoint/superenv/lib/python3.8/site-packages/pytorch_lightning/loops/utilities.py", line 178, in _decorator
    return loop_run(self, *args, **kwargs)
  File "/DATA2/dse411p/Group6_superpoint/superenv/lib/python3.8/site-packages/pytorch_lightning/loops/evaluation_loop.py", line 135, in run
    self._evaluation_step(batch, batch_idx, dataloader_idx, dataloader_iter)
  File "/DATA2/dse411p/Group6_superpoint/superenv/lib/python3.8/site-packages/pytorch_lightning/loops/evaluation_loop.py", line 396, in _evaluation_step
    output = call._call_strategy_hook(trainer, hook_name, *step_args)
  File "/DATA2/dse411p/Group6_superpoint/superenv/lib/python3.8/site-packages/pytorch_lightning/trainer/call.py", line 319, in _call_strategy_hook
    output = fn(*args, **kwargs)
  File "/DATA2/dse411p/Group6_superpoint/superenv/lib/python3.8/site-packages/pytorch_lightning/strategies/strategy.py", line 411, in validation_step
    return self.lightning_module.validation_step(*args, **kwargs)
  File "/DATA2/dse411p/Group6_superpoint/superpoint_transformer/src/models/semantic.py", line 711, in validation_step
    loss, output = self.model_step(batch)
  File "/DATA2/dse411p/Group6_superpoint/superpoint_transformer/src/models/semantic.py", line 324, in model_step
    output = self.step_single_run_inference(batch)
  File "/DATA2/dse411p/Group6_superpoint/superpoint_transformer/src/models/semantic.py", line 473, in step_single_run_inference
    output = self.forward(nag)
  File "/DATA2/dse411p/Group6_superpoint/superpoint_transformer/src/models/semantic.py", line 209, in forward
    x = self.net(nag)
  File "/DATA2/dse411p/Group6_superpoint/superenv/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/DATA2/dse411p/Group6_superpoint/superenv/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
  File "/DATA2/dse411p/Group6_superpoint/superpoint_transformer/src/models/components/spt.py", line 457, in forward
    x, diameter = self.first_stage(
  File "/DATA2/dse411p/Group6_superpoint/superenv/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/DATA2/dse411p/Group6_superpoint/superenv/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
  File "/DATA2/dse411p/Group6_superpoint/superpoint_transformer/src/nn/stage.py", line 233, in forward
    x = self.in_mlp(x, batch=norm_index)
  File "/DATA2/dse411p/Group6_superpoint/superenv/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/DATA2/dse411p/Group6_superpoint/superenv/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
  File "/DATA2/dse411p/Group6_superpoint/superpoint_transformer/src/nn/mlp.py", line 89, in forward
    x = module(x)
  File "/DATA2/dse411p/Group6_superpoint/superenv/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/DATA2/dse411p/Group6_superpoint/superenv/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
  File "/DATA2/dse411p/Group6_superpoint/superenv/lib/python3.8/site-packages/torch/nn/modules/linear.py", line 119, in forward
    return F.linear(input, self.weight, self.bias)
RuntimeError: mat1 and mat2 shapes cannot be multiplied (79824x4 and 10x32)

so in order to debug this issue can you explain me what is 4 in multiplication with data 79824 and 10 and 32 in mat 2 what doews they signifies weather a number of classes ,batches etc

**Comment by drprojects** [comment]
We strive to provide help for the issues we receive here. Still, due to the large number of requests we receive and our limited capacity, we introduced issue templates which help us get better structured issues to facilitate our (free) work. Please use those.
