### ISSUE TITLE
training not working with Dales dataset

### ISSUE THREAD

**Issue by tfwittwer** [drprojects/superpoint_transformer#2]
Hi,

I've installed spt in an Ubuntu 22.04 VM on WSL2. Installation appears to have been finished successfully. Unfortunately I get errors when trying to run training with Dales. I've manually downloaded the PLY version of Dales and placed the train and test folders in the ~/superpoint_transformer/data/dales/raw folder, but the presence of the data appears to be ignored as it looks like the download is still attempted. I then get this error message:

```bash
[2023-06-17 16:14:05,526][src.datasets.base][INFO] - WARNING: You are about to download DALES data.
[2023-06-17 16:14:05,526][src.datasets.base][INFO] - Files will be organized in the following structure:
[2023-06-17 16:14:05,526][src.datasets.base][INFO] -
    /home/toby/superpoint_transformer/data/dales/
        └── raw/
            └── {train, test}/
                └── {tile_name}.ply

[2023-06-17 16:14:05,527][src.datasets.base][INFO] -
[2023-06-17 16:14:05,527][src.datasets.dales][INFO] - Please, register yourself by filling up the form at https://docs.google.com/forms/d/e/1FAIpQLSefhHMMvN0Uwjnj_vWQgYSvtFOtaoGFWsTIcRuBTnP09NHR7A/viewform?fbzx=5530674395784263977
[2023-06-17 16:14:05,527][src.datasets.dales][INFO] - ***
[2023-06-17 16:14:05,529][src.utils.utils][ERROR] -
Traceback (most recent call last):
  File "/home/toby/superpoint_transformer/src/utils/utils.py", line 45, in wrap
    metric_dict, object_dict = task_func(cfg=cfg)
  File "src/train.py", line 114, in train
    trainer.fit(model=model, datamodule=datamodule, ckpt_path=cfg.get("ckpt_path"))
  File "/home/toby/miniconda3/envs/spt/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 531, in fit
    call._call_and_handle_interrupt(
  File "/home/toby/miniconda3/envs/spt/lib/python3.8/site-packages/pytorch_lightning/trainer/call.py", line 42, in _call_and_handle_interrupt
    return trainer_fn(*args, **kwargs)
  File "/home/toby/miniconda3/envs/spt/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 570, in _fit_impl
    self._run(model, ckpt_path=ckpt_path)
  File "/home/toby/miniconda3/envs/spt/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 927, in _run
    self._data_connector.prepare_data()
  File "/home/toby/miniconda3/envs/spt/lib/python3.8/site-packages/pytorch_lightning/trainer/connectors/data_connector.py", line 94, in prepare_data
    call._call_lightning_datamodule_hook(trainer, "prepare_data")
  File "/home/toby/miniconda3/envs/spt/lib/python3.8/site-packages/pytorch_lightning/trainer/call.py", line 160, in _call_lightning_datamodule_hook
    return fn(*args, **kwargs)
  File "/home/toby/superpoint_transformer/src/datamodules/base.py", line 144, in prepare_data
    self.dataset_class(
  File "/home/toby/superpoint_transformer/src/datasets/base.py", line 193, in __init__
    super().__init__(root, transform, pre_transform, pre_filter)
  File "/home/toby/miniconda3/envs/spt/lib/python3.8/site-packages/torch_geometric/data/in_memory_dataset.py", line 57, in __init__
    super().__init__(root, transform, pre_transform, pre_filter, log)
  File "/home/toby/miniconda3/envs/spt/lib/python3.8/site-packages/torch_geometric/data/dataset.py", line 94, in __init__
    self._download()
  File "/home/toby/miniconda3/envs/spt/lib/python3.8/site-packages/torch_geometric/data/dataset.py", line 199, in _download
    self.download()
  File "/home/toby/superpoint_transformer/src/datasets/base.py", line 447, in download
    self.download_dataset()
  File "/home/toby/superpoint_transformer/src/datasets/dales.py", line 124, in download_dataset
    self.download_zip()
  File "/home/toby/superpoint_transformer/src/datasets/dales.py", line 143, in download_zip
    gdown.download(
  File "/home/toby/miniconda3/envs/spt/lib/python3.8/site-packages/gdown/download.py", line 161, in download
    res = sess.get(url, stream=True, verify=verify)
  File "/home/toby/miniconda3/envs/spt/lib/python3.8/site-packages/requests/sessions.py", line 602, in get
    return self.request("GET", url, **kwargs)
  File "/home/toby/miniconda3/envs/spt/lib/python3.8/site-packages/requests/sessions.py", line 575, in request
    prep = self.prepare_request(req)
  File "/home/toby/miniconda3/envs/spt/lib/python3.8/site-packages/requests/sessions.py", line 486, in prepare_request
    p.prepare(
  File "/home/toby/miniconda3/envs/spt/lib/python3.8/site-packages/requests/models.py", line 368, in prepare
    self.prepare_url(url, params)
  File "/home/toby/miniconda3/envs/spt/lib/python3.8/site-packages/requests/models.py", line 439, in prepare_url
    raise MissingSchema(
requests.exceptions.MissingSchema: Invalid URL '1IW_3xZFGf_A05Qqmv3b1eOjtYj461KFX': No scheme supplied. Perhaps you meant https://1IW_3xZFGf_A05Qqmv3b1eOjtYj461KFX?
[2023-06-17 16:14:05,542][src.utils.utils][INFO] - Closing loggers...
[2023-06-17 16:14:05,542][src.utils.utils][INFO] - Closing wandb!
wandb: Waiting for W&B process to finish... (success).
wandb: You can sync this run to the cloud by running:
wandb: wandb sync /home/toby/superpoint_transformer/logs/train/runs/2023-06-17_16-13-53/wandb/offline-run-20230617_161400-3edj9ae0
wandb: Find logs at: ./logs/train/runs/2023-06-17_16-13-53/wandb/offline-run-20230617_161400-3edj9ae0/logs
Error executing job with overrides: ['experiment=dales']
Traceback (most recent call last):
  File "src/train.py", line 139, in main
    metric_dict, _ = train(cfg)
  File "/home/toby/superpoint_transformer/src/utils/utils.py", line 48, in wrap
    raise ex
  File "/home/toby/superpoint_transformer/src/utils/utils.py", line 45, in wrap
    metric_dict, object_dict = task_func(cfg=cfg)
  File "src/train.py", line 114, in train
    trainer.fit(model=model, datamodule=datamodule, ckpt_path=cfg.get("ckpt_path"))
  File "/home/toby/miniconda3/envs/spt/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 531, in fit
    call._call_and_handle_interrupt(
  File "/home/toby/miniconda3/envs/spt/lib/python3.8/site-packages/pytorch_lightning/trainer/call.py", line 42, in _call_and_handle_interrupt
    return trainer_fn(*args, **kwargs)
  File "/home/toby/miniconda3/envs/spt/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 570, in _fit_impl
    self._run(model, ckpt_path=ckpt_path)
  File "/home/toby/miniconda3/envs/spt/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 927, in _run
    self._data_connector.prepare_data()
  File "/home/toby/miniconda3/envs/spt/lib/python3.8/site-packages/pytorch_lightning/trainer/connectors/data_connector.py", line 94, in prepare_data
    call._call_lightning_datamodule_hook(trainer, "prepare_data")
  File "/home/toby/miniconda3/envs/spt/lib/python3.8/site-packages/pytorch_lightning/trainer/call.py", line 160, in _call_lightning_datamodule_hook
    return fn(*args, **kwargs)
  File "/home/toby/superpoint_transformer/src/datamodules/base.py", line 144, in prepare_data
    self.dataset_class(
  File "/home/toby/superpoint_transformer/src/datasets/base.py", line 193, in __init__
    super().__init__(root, transform, pre_transform, pre_filter)
  File "/home/toby/miniconda3/envs/spt/lib/python3.8/site-packages/torch_geometric/data/in_memory_dataset.py", line 57, in __init__
    super().__init__(root, transform, pre_transform, pre_filter, log)
  File "/home/toby/miniconda3/envs/spt/lib/python3.8/site-packages/torch_geometric/data/dataset.py", line 94, in __init__
    self._download()
  File "/home/toby/miniconda3/envs/spt/lib/python3.8/site-packages/torch_geometric/data/dataset.py", line 199, in _download
    self.download()
  File "/home/toby/superpoint_transformer/src/datasets/base.py", line 447, in download
    self.download_dataset()
  File "/home/toby/superpoint_transformer/src/datasets/dales.py", line 124, in download_dataset
    self.download_zip()
  File "/home/toby/superpoint_transformer/src/datasets/dales.py", line 143, in download_zip
    gdown.download(
  File "/home/toby/miniconda3/envs/spt/lib/python3.8/site-packages/gdown/download.py", line 161, in download
    res = sess.get(url, stream=True, verify=verify)
  File "/home/toby/miniconda3/envs/spt/lib/python3.8/site-packages/requests/sessions.py", line 602, in get
    return self.request("GET", url, **kwargs)
  File "/home/toby/miniconda3/envs/spt/lib/python3.8/site-packages/requests/sessions.py", line 575, in request
    prep = self.prepare_request(req)
  File "/home/toby/miniconda3/envs/spt/lib/python3.8/site-packages/requests/sessions.py", line 486, in prepare_request
    p.prepare(
  File "/home/toby/miniconda3/envs/spt/lib/python3.8/site-packages/requests/models.py", line 368, in prepare
    self.prepare_url(url, params)
  File "/home/toby/miniconda3/envs/spt/lib/python3.8/site-packages/requests/models.py", line 439, in prepare_url
    raise MissingSchema(
requests.exceptions.MissingSchema: Invalid URL '1IW_3xZFGf_A05Qqmv3b1eOjtYj461KFX': No scheme supplied. Perhaps you meant https://1IW_3xZFGf_A05Qqmv3b1eOjtYj461KFX?

Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace.
```

Additionally, I think it would be very nice and useful if there was a dataset class that could operate on LAS/LAZ files.

**Comment by drprojects** [comment]
Hi, thanks for using our repo ! 

It seems the automatic download of DALES fails on your machine. Other users ran into similar issues with S3DIS. I am considering removing this auto-download feature which is not stable on all distributions. 

The latest commit provides more instructions in [`docs/datasets.md`](https://github.com/drprojects/superpoint_transformer/blob/master/docs/datasets.md) as per how to organise your dataset files and where to download them from. 

Can you please try setting up your DALES dataset manually by downloading the `DALESObjects.tar.gz` from [here](https://docs.google.com/forms/d/e/1FAIpQLSefhHMMvN0Uwjnj_vWQgYSvtFOtaoGFWsTIcRuBTnP09NHR7A/viewform?fbzx=5530674395784263977) and placing the files in the appropriate structure described in [`docs/datasets.md`](https://github.com/drprojects/superpoint_transformer/blob/master/docs/datasets.md) ?

Let me know if this solves your issue.

**Comment by drprojects** [comment]
Regarding your second comment on `LAS/LAZ` datasets, the current release only supports the datasets we evaluate our method on in our [paper](https://arxiv.org/abs/2306.08045). 

It should be relatively easy to extend the current code to other datasets. See [`docs/datasets`](https://github.com/drprojects/superpoint_transformer/blob/master/docs/datasets.md) and the docstrings of the referred base classes for that. If you are specifically interested in a python LAS reader, I could recommend using [laspy](https://laspy.readthedocs.io/). 

If you wanted to introduce a new dataset to this project, we would gladly welcome a pull request !

**Comment by drprojects** [comment]
Hi, did you manage to successfully install DALES from manually downloadded data ? If not, the latest commit should make it clearer how to. See the [`docs/datasets`](https://github.com/drprojects/superpoint_transformer/blob/master/docs/datasets.md) for more information.

Please let me know if that solves your issue.

**Comment by drprojects** [comment]
Have you managed to run the code on DALES ?

**Comment by tfwittwer** [comment]
I haven't found the time yet to give it a go, I'll let you know when I have. :-)

**Comment by drprojects** [comment]
I close this issue for now. Feel free to re-open it if relevant.
