### ISSUE TITLE
Custom Dataset - AssertionError: Cloud ids must be unique across all the 'val' and 'test' stages, unless `test_mixed_in_val=True`

### ISSUE THREAD

**Issue by StevenZhangzhexu** [drprojects/superpoint_transformer#48]
Hi Damien,

I tried to train the model in a custom dataset but encounter below error. (I have followed the docs to set up env, dataset & configs)

```python
Traceback (most recent call last):
  File "/home/steven/Desktop/git/superpoint_transformer/src/utils/utils.py", line 45, in wrap
    metric_dict, object_dict = task_func(cfg=cfg)
  File "src/train.py", line 114, in train
    trainer.fit(model=model, datamodule=datamodule, ckpt_path=cfg.get("ckpt_path"))
  File "/home/steven/miniconda3/envs/spt/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 544, in fit
    call._call_and_handle_interrupt(
  File "/home/steven/miniconda3/envs/spt/lib/python3.8/site-packages/pytorch_lightning/trainer/call.py", line 44, in _call_and_handle_interrupt
    return trainer_fn(*args, **kwargs)
  File "/home/steven/miniconda3/envs/spt/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 580, in _fit_impl
    self._run(model, ckpt_path=ckpt_path)
  File "/home/steven/miniconda3/envs/spt/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 989, in _run
    results = self._run_stage()
  File "/home/steven/miniconda3/envs/spt/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1033, in _run_stage
    self._run_sanity_check()
  File "/home/steven/miniconda3/envs/spt/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1062, in _run_sanity_check
    val_loop.run()
  File "/home/steven/miniconda3/envs/spt/lib/python3.8/site-packages/pytorch_lightning/loops/utilities.py", line 182, in _decorator
    return loop_run(self, *args, **kwargs)
  File "/home/steven/miniconda3/envs/spt/lib/python3.8/site-packages/pytorch_lightning/loops/evaluation_loop.py", line 134, in run
    self._evaluation_step(batch, batch_idx, dataloader_idx, dataloader_iter)
  File "/home/steven/miniconda3/envs/spt/lib/python3.8/site-packages/pytorch_lightning/loops/evaluation_loop.py", line 365, in _evaluation_step
    batch = call._call_strategy_hook(trainer, "batch_to_device", batch, dataloader_idx=dataloader_idx)
  File "/home/steven/miniconda3/envs/spt/lib/python3.8/site-packages/pytorch_lightning/trainer/call.py", line 309, in _call_strategy_hook
    output = fn(*args, **kwargs)
  File "/home/steven/miniconda3/envs/spt/lib/python3.8/site-packages/pytorch_lightning/strategies/strategy.py", line 269, in batch_to_device
    return model._apply_batch_transfer_handler(batch, device=device, dataloader_idx=dataloader_idx)
  File "/home/steven/miniconda3/envs/spt/lib/python3.8/site-packages/pytorch_lightning/core/module.py", line 334, in _apply_batch_transfer_handler
    batch = self._call_batch_hook("on_after_batch_transfer", batch, dataloader_idx)
  File "/home/steven/miniconda3/envs/spt/lib/python3.8/site-packages/pytorch_lightning/core/module.py", line 322, in _call_batch_hook
    return trainer_method(trainer, hook_name, *args)
  File "/home/steven/miniconda3/envs/spt/lib/python3.8/site-packages/pytorch_lightning/trainer/call.py", line 179, in _call_lightning_datamodule_hook
    return fn(*args, **kwargs)
  File "/home/steven/miniconda3/envs/spt/lib/python3.8/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/home/steven/Desktop/git/superpoint_transformer/src/datamodules/base.py", line 336, in on_after_batch_transfer
    return on_device_transform(nag)
  File "/home/steven/miniconda3/envs/spt/lib/python3.8/site-packages/torch_geometric/transforms/compose.py", line 24, in __call__
    data = transform(data)
  File "/home/steven/Desktop/git/superpoint_transformer/src/transforms/transforms.py", line 23, in __call__
    return self._process(x)
  File "/home/steven/Desktop/git/superpoint_transformer/src/transforms/data.py", line 347, in _process
    raise ValueError(
ValueError: Input NAG does not have `is_val` attribute at level `0`
```

My data directory is like this:
```
/data/DATASET/
        └── raw/
            └── {train, test}/
                └── {file_name}.laz
```
            
and I want to train on train files and test on test files. In this case there is no validation dataset, is it condisered `test_mixed_in_val` ?
Could you please help on this? Thanks!

**Comment by drprojects** [comment]
Hi @StevenZhangzhexu 

Could you try setting:

```yaml
trainval: False
val_on_test: True
```

in your dataset config file ? 

PS: if you are interested in this project, don't forget to give the repo a ⭐, it matters to us !

**Comment by StevenZhangzhexu** [comment]
I set `strict= False` to bypass the assertion error. But not sure if this will affect the traning result?

**Comment by drprojects** [comment]
> I set strict= False to bypass the assertion error. But not sure if this will affect the traning result?

I am not sure where you set that, but I would not recommend it. Try to fix the error by making sure you have not set `val_mixed_in_train=True` or `test_mixed_in_val=True` somewhere first.

**Comment by wy9933** [comment]
Hello, I have the same problem, my Val and Test are same dataset, and if I use
``` Python
test_mixed_in_val: False
val_mixed_in_test: False
trainval: False
val_on_test: True
```

The code will raise
> AssertionError: Cloud ids must be unique across all the 'val' and 'test' stages, unless `test_mixed_in_val=True

If  I set ’test_mixed_in_val: True‘ , The code will raise
> ValueError: Input NAG does not have `is_val` attribute at level `0`

**Comment by drprojects** [comment]
Hi @StevenZhangzhexu and @wy9933. I confirm that you should not set  `test_mixed_in_val=True` in your setting. The true error we need to investigate is:

> AssertionError: Cloud ids must be unique across all the 'val' and 'test' stages, unless `test_mixed_in_val=True

Can you please show me how you implemented your dataset's `all_base_cloud_ids()` ?

```python 
def all_base_cloud_ids(self):
...
```

**Comment by wy9933** [comment]
My dataset's `all_base_cloud_ids()` is
```Python
def all_base_cloud_ids(self):
    return {
        'train': [SCENES[i] for i in range(7) if i != self.test_idx],
        'val': [SCENES[self.test_idx]],
        'test': [SCENES[self.test_idx]]
    }
```
And `SCENES` is a file list of all point cloud scene name. So the Val and Test are same dataset.
If I set `test_mixed_in_val=False`, the `assert` in `check_cloud_ids` in `src/datasets/base.py` will raise Error:
```Python
assert len(val.intersection(test)) == 0 or self.test_mixed_in_val, \
            "Cloud ids must be unique across all the 'val' and 'test' " \
            "stages, unless `test_mixed_in_val=True`"
```

**Comment by drprojects** [comment]
OK this is probably where the error comes from. You should set:

```python
def all_base_cloud_ids(self):
    return {
        'train': [SCENES[i] for i in range(7) if i != self.test_idx],  # list of clouds in your train set
        'val': [],  # empty because you have no validation clouds
        'test': [SCENES[self.test_idx]]  # list of clouds in your test set
    }
```

You do not have validation clouds per se, so you should set an empty list there. Setting `val_on_test=True` will let the program know that it should use your `test` for the `val` stage too.

**Comment by wy9933** [comment]
OK! It's working! Thanks for your answer!

**Comment by drprojects** [comment]
Cool ! Thanks for the feedback :wink:
