### ISSUE TITLE
how to get evaluation metrics on validation data[kitti-360]? where should I mention that to get evaluation metrics?

### ISSUE THREAD

**Issue by meehirmhatrepy** [drprojects/superpoint_transformer#90]
how to get evaluation metrics on validation data[kitti-360]? where should I mention that to get evaluation metrics?

_Originally posted by @meehirmhatrepy in https://github.com/drprojects/superpoint_transformer/issues/30#issuecomment-2031487313_

**Comment by drprojects** [comment]
The metrics are computed by default when you train a model on KITTI-360. 

Tet, if you want to compute metrics on the validation set using our pretrained model, you can do so with minor modifications to the `eval.py` script. Replace:

```python
trainer.test(model=model, datamodule=datamodule, ckpt_path=cfg.ckpt_path)
```

by 

```python
trainer.validate(model=model, datamodule=datamodule, ckpt_path=cfg.ckpt_path)
```

This is `PyTorch Lightning` syntax. The main difference is that the former will use `datamodule.test_dataloader()`, while the latter will use `datamodule.val_dataloader()`.

Then running the following should compute validation metrics for KITTI-360:

```bash
python src/eval.py experiment=kitti360  ckpt_path='downloaded checkpoint from your website'
```

PS: If you ❤️ or use this project, don't forget to give it a ⭐, it means a lot to us !

**Comment by meehirmhatrepy** [comment]
I have tried that. but it gave another error: 

[2024-04-02 11:02:42,888][src.datasets.base][INFO] - Preprocessed data can be found at: "C:\Users\mmhatre\Downloads\superpoint_transformer-master\data\kitti360\processed\<stage>\c67bf715d56b70e632f9ebcfddd71d8d"
Restoring states from the checkpoint path at [C:/Users/mmhatre/Downloads/superpoint_transformer-master/supercluster_kitti360.ckpt](file:///C:/Users/mmhatre/Downloads/superpoint_transformer-master/supercluster_kitti360.ckpt)
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]
Loaded model weights from checkpoint at [C:/Users/mmhatre/Downloads/superpoint_transformer-master/supercluster_kitti360.ckpt](file:///C:/Users/mmhatre/Downloads/superpoint_transformer-master/supercluster_kitti360.ckpt)
Validation: 
 0/? [00:00<?, ?it/s]
[2024-04-02 11:02:43,399][src.utils.utils][ERROR] - 
Traceback (most recent call last):
  File "c:\Users\mmhatre\Downloads\superpoint_transformer-master\src\utils\utils.py", line 45, in wrap
    metric_dict, object_dict = task_func(cfg=cfg)
  File "C:\Users\mmhatre\Downloads\superpoint_transformer-master\src\eval.py", line 105, in evaluate
    trainer.validate(model=model, datamodule=datamodule, ckpt_path=cfg.ckpt_path)
  File "c:\Users\mmhatre\AppData\Local\anaconda3\envs\sptx\lib\site-packages\pytorch_lightning\trainer\trainer.py", line 662, in validate
    return call._call_and_handle_interrupt(
  File "c:\Users\mmhatre\AppData\Local\anaconda3\envs\sptx\lib\site-packages\pytorch_lightning\trainer\call.py", line 38, in _call_and_handle_interrupt
    return trainer_fn(*args, **kwargs)
  File "c:\Users\mmhatre\AppData\Local\anaconda3\envs\sptx\lib\site-packages\pytorch_lightning\trainer\trainer.py", line 711, in _validate_impl
    results = self._run(model, ckpt_path=self.ckpt_path)
  File "c:\Users\mmhatre\AppData\Local\anaconda3\envs\sptx\lib\site-packages\pytorch_lightning\trainer\trainer.py", line 1058, in _run
    results = self._run_stage()
  File "c:\Users\mmhatre\AppData\Local\anaconda3\envs\sptx\lib\site-packages\pytorch_lightning\trainer\trainer.py", line 1134, in _run_stage
    return self._run_evaluate()
  File "c:\Users\mmhatre\AppData\Local\anaconda3\envs\sptx\lib\site-packages\pytorch_lightning\trainer\trainer.py", line 1174, in _run_evaluate
    eval_loop_results = self._evaluation_loop.run()
  File "c:\Users\mmhatre\AppData\Local\anaconda3\envs\sptx\lib\site-packages\pytorch_lightning\loops\loop.py", line 199, in run
    self.advance(*args, **kwargs)
  File "c:\Users\mmhatre\AppData\Local\anaconda3\envs\sptx\lib\site-packages\pytorch_lightning\loops\dataloader\evaluation_loop.py", line 152, in advance
    dl_outputs = self.epoch_loop.run(self._data_fetcher, dl_max_batches, kwargs)
  File "c:\Users\mmhatre\AppData\Local\anaconda3\envs\sptx\lib\site-packages\pytorch_lightning\loops\loop.py", line 194, in run
    self.on_run_start(*args, **kwargs)
  File "c:\Users\mmhatre\AppData\Local\anaconda3\envs\sptx\lib\site-packages\pytorch_lightning\loops\epoch\evaluation_epoch_loop.py", line 84, in on_run_start
    self._data_fetcher = iter(data_fetcher)
  File "c:\Users\mmhatre\AppData\Local\anaconda3\envs\sptx\lib\site-packages\pytorch_lightning\utilities\fetching.py", line 178, in __iter__
    self.dataloader_iter = iter(self.dataloader)
  File "c:\Users\mmhatre\AppData\Local\anaconda3\envs\sptx\lib\site-packages\torch\utils\data\dataloader.py", line 434, in __iter__
    self._iterator = self._get_iterator()
  File "c:\Users\mmhatre\AppData\Local\anaconda3\envs\sptx\lib\site-packages\torch\utils\data\dataloader.py", line 387, in _get_iterator
    return _MultiProcessingDataLoaderIter(self)
  File "c:\Users\mmhatre\AppData\Local\anaconda3\envs\sptx\lib\site-packages\torch\utils\data\dataloader.py", line 1040, in __init__
    w.start()
  File "c:\Users\mmhatre\AppData\Local\anaconda3\envs\sptx\lib\multiprocessing\process.py", line 121, in start
    self._popen = self._Popen(self)
  File "c:\Users\mmhatre\AppData\Local\anaconda3\envs\sptx\lib\multiprocessing\context.py", line 224, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "c:\Users\mmhatre\AppData\Local\anaconda3\envs\sptx\lib\multiprocessing\context.py", line 327, in _Popen
    return Popen(process_obj)
  File "c:\Users\mmhatre\AppData\Local\anaconda3\envs\sptx\lib\multiprocessing\popen_spawn_win32.py", line 45, in __init__
    prep_data = spawn.get_preparation_data(process_obj._name)
  File "c:\Users\mmhatre\AppData\Local\anaconda3\envs\sptx\lib\multiprocessing\spawn.py", line 183, in get_preparation_data
    main_mod_name = getattr(main_module.__spec__, "name", None)
AttributeError: module '__main__' has no attribute '__spec__'
[2024-04-02 11:02:43,399][src.utils.utils][INFO] - Closing loggers...
Error executing job with overrides: ['experiment=panoptic/kitti360', 'ckpt_path=C:/Users/mmhatre/Downloads/superpoint_transformer-master/supercluster_kitti360.ckpt']
Traceback (most recent call last):
  File "C:\Users\mmhatre\Downloads\superpoint_transformer-master\src\eval.py", line 117, in main
    evaluate(cfg)
  File "c:\Users\mmhatre\Downloads\superpoint_transformer-master\src\utils\utils.py", line 48, in wrap
    raise ex
  File "c:\Users\mmhatre\Downloads\superpoint_transformer-master\src\utils\utils.py", line 45, in wrap
    metric_dict, object_dict = task_func(cfg=cfg)
  File "C:\Users\mmhatre\Downloads\superpoint_transformer-master\src\eval.py", line 105, in evaluate
    trainer.validate(model=model, datamodule=datamodule, ckpt_path=cfg.ckpt_path)
  File "c:\Users\mmhatre\AppData\Local\anaconda3\envs\sptx\lib\site-packages\pytorch_lightning\trainer\trainer.py", line 662, in validate
    return call._call_and_handle_interrupt(
  File "c:\Users\mmhatre\AppData\Local\anaconda3\envs\sptx\lib\site-packages\pytorch_lightning\trainer\call.py", line 38, in _call_and_handle_interrupt
    return trainer_fn(*args, **kwargs)
  File "c:\Users\mmhatre\AppData\Local\anaconda3\envs\sptx\lib\site-packages\pytorch_lightning\trainer\trainer.py", line 711, in _validate_impl
    results = self._run(model, ckpt_path=self.ckpt_path)
  File "c:\Users\mmhatre\AppData\Local\anaconda3\envs\sptx\lib\site-packages\pytorch_lightning\trainer\trainer.py", line 1058, in _run
    results = self._run_stage()
  File "c:\Users\mmhatre\AppData\Local\anaconda3\envs\sptx\lib\site-packages\pytorch_lightning\trainer\trainer.py", line 1134, in _run_stage
    return self._run_evaluate()
  File "c:\Users\mmhatre\AppData\Local\anaconda3\envs\sptx\lib\site-packages\pytorch_lightning\trainer\trainer.py", line 1174, in _run_evaluate
    eval_loop_results = self._evaluation_loop.run()
  File "c:\Users\mmhatre\AppData\Local\anaconda3\envs\sptx\lib\site-packages\pytorch_lightning\loops\loop.py", line 199, in run
    self.advance(*args, **kwargs)
  File "c:\Users\mmhatre\AppData\Local\anaconda3\envs\sptx\lib\site-packages\pytorch_lightning\loops\dataloader\evaluation_loop.py", line 152, in advance
    dl_outputs = self.epoch_loop.run(self._data_fetcher, dl_max_batches, kwargs)
  File "c:\Users\mmhatre\AppData\Local\anaconda3\envs\sptx\lib\site-packages\pytorch_lightning\loops\loop.py", line 194, in run
    self.on_run_start(*args, **kwargs)
  File "c:\Users\mmhatre\AppData\Local\anaconda3\envs\sptx\lib\site-packages\pytorch_lightning\loops\epoch\evaluation_epoch_loop.py", line 84, in on_run_start
    self._data_fetcher = iter(data_fetcher)
  File "c:\Users\mmhatre\AppData\Local\anaconda3\envs\sptx\lib\site-packages\pytorch_lightning\utilities\fetching.py", line 178, in __iter__
    self.dataloader_iter = iter(self.dataloader)
  File "c:\Users\mmhatre\AppData\Local\anaconda3\envs\sptx\lib\site-packages\torch\utils\data\dataloader.py", line 434, in __iter__
    self._iterator = self._get_iterator()
  File "c:\Users\mmhatre\AppData\Local\anaconda3\envs\sptx\lib\site-packages\torch\utils\data\dataloader.py", line 387, in _get_iterator
    return _MultiProcessingDataLoaderIter(self)
  File "c:\Users\mmhatre\AppData\Local\anaconda3\envs\sptx\lib\site-packages\torch\utils\data\dataloader.py", line 1040, in __init__
    w.start()
  File "c:\Users\mmhatre\AppData\Local\anaconda3\envs\sptx\lib\multiprocessing\process.py", line 121, in start
    self._popen = self._Popen(self)
  File "c:\Users\mmhatre\AppData\Local\anaconda3\envs\sptx\lib\multiprocessing\context.py", line 224, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "c:\Users\mmhatre\AppData\Local\anaconda3\envs\sptx\lib\multiprocessing\context.py", line 327, in _Popen
    return Popen(process_obj)
  File "c:\Users\mmhatre\AppData\Local\anaconda3\envs\sptx\lib\multiprocessing\popen_spawn_win32.py", line 45, in __init__
    prep_data = spawn.get_preparation_data(process_obj._name)
  File "c:\Users\mmhatre\AppData\Local\anaconda3\envs\sptx\lib\multiprocessing\spawn.py", line 183, in get_preparation_data
    main_mod_name = getattr(main_module.__spec__, "name", None)
AttributeError: module '__main__' has no attribute '__spec__'
