### ISSUE TITLE
No module named 'frnn'

### ISSUE THREAD

**Issue by narges-tk** [drprojects/superpoint_transformer#94]
Hi! Thanks for publishing your code! While everything went well in installation phase, now I am getting **No module named 'frnn'** error. Any help would be appreciated. Please find the complete error below.

ntakhtke  ❲c❳ spt  ~/DL_models/superpoint_transformer-master  1  python src/train.py experiment=semantic/narges_data
Traceback (most recent call last):
  File "src/train.py", line 49, in <module>
    from src import utils
  File "/home/ntakhtke/DL_models/superpoint_transformer-master/src/__init__.py", line 2, in <module>
    import src.data
  File "/home/ntakhtke/DL_models/superpoint_transformer-master/src/data/__init__.py", line 1, in <module>
    from .csr import *
  File "/home/ntakhtke/DL_models/superpoint_transformer-master/src/data/csr.py", line 5, in <module>
    from src.utils import tensor_idx, is_sorted, indices_to_pointers, \
  File "/home/ntakhtke/DL_models/superpoint_transformer-master/src/utils/__init__.py", line 12, in <module>
    from .neighbors import *
  File "/home/ntakhtke/DL_models/superpoint_transformer-master/src/utils/neighbors.py", line 3, in <module>
    from src.dependencies.FRNN import frnn
  File "/home/ntakhtke/DL_models/superpoint_transformer-master/src/dependencies/FRNN/frnn/__init__.py", line 2, in <module>
    from .frnn import frnn_grid_points, frnn_gather, frnn_bf_points, _C
  File "/home/ntakhtke/DL_models/superpoint_transformer-master/src/dependencies/FRNN/frnn/frnn.py", line 7, in <module>
    from frnn import _C
ModuleNotFoundError: No module named 'frnn'

**Comment by drprojects** [comment]
Hi @narges-tk, thanks for your interest in this project.

This error comes from the fact that the dependency `FRNN` was not properly installed when running `install.sh`.

This may be related to #77, please check this first.

PS: if you ❤️ or use this project, don't forget to give it a ⭐, it means a lot to us !
