### ISSUE TITLE
mutable default <class 'hydra.conf.JobConf.JobConfig.OverrideDirname'> for field override_dirname is not allowed

### ISSUE THREAD

**Issue by narges-tk** [drprojects/superpoint_transformer#95]
Hi! I am getting the following error. Thanks in advance for any help you could provide.

**ntakhtke  ❲c❳ /home/ntakhtke/anaconda3  ~/DL_models/superpoint_transformer-master  python src/train.py experiment=semantic/DALESObjects
Traceback (most recent call last):
  File "/home/ntakhtke/.local/share/Trash/files/superpoint_transformer-master/src/train.py", line 41, in <module>
    import hydra
  File "/home/ntakhtke/anaconda3/lib/python3.11/site-packages/hydra/__init__.py", line 5, in <module>
    from hydra import utils
  File "/home/ntakhtke/anaconda3/lib/python3.11/site-packages/hydra/utils.py", line 8, in <module>
    import hydra._internal.instantiate._instantiate2
  File "/home/ntakhtke/anaconda3/lib/python3.11/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 12, in <module>
    from hydra._internal.utils import _locate
  File "/home/ntakhtke/anaconda3/lib/python3.11/site-packages/hydra/_internal/utils.py", line 18, in <module>
    from hydra.core.utils import get_valid_filename, validate_config_path
  File "/home/ntakhtke/anaconda3/lib/python3.11/site-packages/hydra/core/utils.py", line 20, in <module>
    from hydra.core.hydra_config import HydraConfig
  File "/home/ntakhtke/anaconda3/lib/python3.11/site-packages/hydra/core/hydra_config.py", line 6, in <module>
    from hydra.conf import HydraConf
  File "/home/ntakhtke/anaconda3/lib/python3.11/site-packages/hydra/conf/__init__.py", line 46, in <module>
    class JobConf:
  File "/home/ntakhtke/anaconda3/lib/python3.11/site-packages/hydra/conf/__init__.py", line 75, in JobConf
    @dataclass
     ^^^^^^^^^
  File "/home/ntakhtke/anaconda3/lib/python3.11/dataclasses.py", line 1230, in dataclass
    return wrap(cls)
           ^^^^^^^^^
  File "/home/ntakhtke/anaconda3/lib/python3.11/dataclasses.py", line 1220, in wrap
    return _process_class(cls, init, repr, eq, order, unsafe_hash,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ntakhtke/anaconda3/lib/python3.11/dataclasses.py", line 958, in _process_class
    cls_fields.append(_get_field(cls, name, type, kw_only))
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ntakhtke/anaconda3/lib/python3.11/dataclasses.py", line 815, in _get_field
    raise ValueError(f'mutable default {type(f.default)} for field '
ValueError: mutable default <class 'hydra.conf.JobConf.JobConfig.OverrideDirname'> for field override_dirname is not allowed: use default_factory**

**Comment by gvoysey** [comment]
3.11 is too new: https://docs.python.org/3/library/dataclasses.html#mutable-default-values

use 3.10 instead.

**Comment by narges-tk** [comment]
> 3.11 is too new: https://docs.python.org/3/library/dataclasses.html#mutable-default-values
> 
> use 3.10 instead.

Thanks! Resolved. Python version of ./install.sh is fine!
